// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxtlMFoUQHVDPW5M7CU8VJv22Ek8ljrjQ',
    appId: '1:923020113245:web:00d2dac28981ec1b97a4b4',
    messagingSenderId: '923020113245',
    projectId: 'time-table-app-85f29',
    authDomain: 'time-table-app-85f29.firebaseapp.com',
    storageBucket: 'time-table-app-85f29.appspot.com',
    measurementId: 'G-RVKX4LBS5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwon_Fn2mopfDCvjTffL9kGeKu4gakpI0',
    appId: '1:923020113245:android:e3e3342c2ab40e3a97a4b4',
    messagingSenderId: '923020113245',
    projectId: 'time-table-app-85f29',
    storageBucket: 'time-table-app-85f29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeyZaAEqdebQfsk5CvKraLhov27yTZByo',
    appId: '1:923020113245:ios:77aab6f27a9efd2497a4b4',
    messagingSenderId: '923020113245',
    projectId: 'time-table-app-85f29',
    storageBucket: 'time-table-app-85f29.appspot.com',
    iosClientId: '923020113245-6uqoe32g1ks4sfl9j17m95s85kjgrf4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTableApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeyZaAEqdebQfsk5CvKraLhov27yTZByo',
    appId: '1:923020113245:ios:4ae50c2f5e381fe997a4b4',
    messagingSenderId: '923020113245',
    projectId: 'time-table-app-85f29',
    storageBucket: 'time-table-app-85f29.appspot.com',
    iosClientId: '923020113245-mobmu3470uuomi6pdrrvu4u0udgno8mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTableApp.RunnerTests',
  );
}
